// <auto-generated />
using System;
using HukukTakip.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HukukTakip.Api.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251015121955_Musteri_v2")]
    partial class Musteri_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Avukat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BaroNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("avukatlar", (string)null);
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Icra.IcraDosyasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DosyaTuru")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("IcraDairesi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OlusturanUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihiUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("TakipTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DosyaNo")
                        .IsUnique();

                    b.ToTable("IcraDosyalari", (string)null);
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Ihtar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IhtarNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("IhtarTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IhtarTebligGirisTarihi")
                        .HasColumnType("date");

                    b.Property<decimal>("IhtarnameGayriNakitTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IhtarnameNakitTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IhtarnameSuresiGun")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("KatTarihi")
                        .HasColumnType("date");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MusteriUrunleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoterAdi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OlusturanUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihiUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("TebligTarihi")
                        .HasColumnType("date");

                    b.Property<string>("YevmiyeNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IhtarNo")
                        .IsUnique()
                        .HasFilter("[IhtarNo] IS NOT NULL");

                    b.HasIndex("MusteriId");

                    b.HasIndex("YevmiyeNo")
                        .IsUnique()
                        .HasFilter("[YevmiyeNo] IS NOT NULL");

                    b.HasIndex("NoterAdi", "YevmiyeNo")
                        .IsUnique()
                        .HasFilter("[NoterAdi] IS NOT NULL AND [YevmiyeNo] IS NOT NULL");

                    b.ToTable("Ihtarlar", (string)null);
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Musteri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdiUnvani")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AileSiraNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnneAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BabaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BorcluSoyadi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BorcluTipi")
                        .HasColumnType("int");

                    b.Property<string>("BorcuTipi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CiltNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("DogumYeri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HayattaMi")
                        .HasColumnType("bit");

                    b.Property<int?>("IlceId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("KimlikVerilisTarihi")
                        .HasColumnType("date");

                    b.Property<string>("KutukSiraNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MedeniDurum")
                        .HasColumnType("int");

                    b.Property<int>("MusteriMusteriTipi")
                        .HasColumnType("int");

                    b.Property<string>("MusteriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NufusaKayitliOlduguIl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OlusturanUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihiUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasaportNumarasi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SSKIsyeriNumarasi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SSKNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SehirId")
                        .HasColumnType("int");

                    b.Property<string>("Semt")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SurucuBelgesiNumarasi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TCKN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TicaretSicilNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriNo")
                        .IsUnique();

                    b.HasIndex("SehirId");

                    b.HasIndex("TCKN")
                        .IsUnique()
                        .HasFilter("[TCKN] IS NOT NULL");

                    b.HasIndex("VergiNo")
                        .IsUnique()
                        .HasFilter("[VergiNo] IS NOT NULL");

                    b.ToTable("Musteriler", (string)null);
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Sozluk.DavaTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("DavaTurleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "İcra"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Aile"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Ceza"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İş"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Tüketici"
                        });
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Sozluk.IcraDairesi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("UYAP_BRM_TUR_ACKLM");

                    b.Property<int>("SehirId")
                        .HasColumnType("int")
                        .HasColumnName("UYAP_IL_KOD");

                    b.HasKey("Id");

                    b.HasIndex("SehirId");

                    b.ToTable("IcraDaireleri", (string)null);
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Sozluk.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlakaKodu")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Ad");

                    b.ToTable("Sehirler", (string)null);
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Urun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("urunler", (string)null);
                });

            modelBuilder.Entity("HukukTakip.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@demo.com",
                            KayitTarihi = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            KullaniciAdi = "admin",
                            Rol = "admin",
                            SifreHash = "$2a$11$DJUpOEmwBejBEoH.cGQQGueUPIhIWYHbpXkiTK7edw2fL.r9pC472"
                        });
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Ihtar", b =>
                {
                    b.HasOne("HukukTakip.Api.Domain.Entities.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Musteri", b =>
                {
                    b.HasOne("HukukTakip.Api.Domain.Entities.Sozluk.Sehir", null)
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Sozluk.IcraDairesi", b =>
                {
                    b.HasOne("HukukTakip.Api.Domain.Entities.Sozluk.Sehir", "Sehir")
                        .WithMany("IcraDaireleri")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("HukukTakip.Api.Domain.Entities.Sozluk.Sehir", b =>
                {
                    b.Navigation("IcraDaireleri");
                });
#pragma warning restore 612, 618
        }
    }
}
