using HukukTakip.Api.Domain.Enums;

namespace HukukTakip.Api.Application.DTOs;

public record AvukatListDto(
    Guid Id,
    string Adi,
    string Soyadi
);

public record AvukatDetailDto(
    Guid Id,
    string Adi,
    string Soyadi,
    string? TCKN,
    string? VergiDairesi,
    string? VergiNo,
    string? Email,
    DateOnly? DogumTarihi,
    string? CepTelefonu,
    string? IsTelefonu,
    string? IsFaxNo,
    int? SehirId,
    int? IlceId,
    string? TamAdres,
    int? AvansHesapSubeId,
    string? AvansHesapNo,
    int? VadesizHesapSubeId,
    string? VadesizHesapNo,
    string? HalkbankVadesizIbanNo,
    string? DigerBankaIbanNo,
    decimal AvansLimiti,
    AvukatTipi? AvukatTipi,
    bool IletisimVeribanMi,
    bool Dialogdan,
    bool DialogYasal,
    bool Normal,
    bool HesapAktifMi
);

public record AvukatCreateDto(
    string Adi,
    string Soyadi,
    string? TCKN,
    string? VergiDairesi,
    string? VergiNo,
    string? Email,
    DateOnly? DogumTarihi,
    string? CepTelefonu,
    string? IsTelefonu,
    string? IsFaxNo,
    int? SehirId,
    int? IlceId,
    string? TamAdres,
    int? AvansHesapSubeId,
    string? AvansHesapNo,
    int? VadesizHesapSubeId,
    string? VadesizHesapNo,
    string? HalkbankVadesizIbanNo,
    string? DigerBankaIbanNo,
    decimal AvansLimiti,
    AvukatTipi? AvukatTipi,
    bool IletisimVeribanMi,
    bool Dialogdan,
    bool DialogYasal,
    bool Normal,
    bool HesapAktifMi
);

public record AvukatUpdateDto(
    string Adi,
    string Soyadi,
    string? TCKN,
    string? VergiDairesi,
    string? VergiNo,
    string? Email,
    DateOnly? DogumTarihi,
    string? CepTelefonu,
    string? IsTelefonu,
    string? IsFaxNo,
    int? SehirId,
    int? IlceId,
    string? TamAdres,
    int? AvansHesapSubeId,
    string? AvansHesapNo,
    int? VadesizHesapSubeId,
    string? VadesizHesapNo,
    string? HalkbankVadesizIbanNo,
    string? DigerBankaIbanNo,
    decimal AvansLimiti,
    AvukatTipi? AvukatTipi,
    bool IletisimVeribanMi,
    bool Dialogdan,
    bool DialogYasal,
    bool Normal,
    bool HesapAktifMi
);
public record AvukatDeleteDto(
    string Adi,
    string Soyadi,
    string? TCKN,
    string? VergiDairesi,
    string? VergiNo,
    string? Email,
    DateOnly? DogumTarihi,
    string? CepTelefonu,
    string? IsTelefonu,
    string? IsFaxNo,
    int? SehirId,
    int? IlceId,
    string? TamAdres,
    int? AvansHesapSubeId,
    string? AvansHesapNo,
    int? VadesizHesapSubeId,
    string? VadesizHesapNo,
    string? HalkbankVadesizIbanNo,
    string? DigerBankaIbanNo,
    decimal AvansLimiti,
    AvukatTipi? AvukatTipi,
    bool IletisimVeribanMi,
    bool Dialogdan,
    bool DialogYasal,
    bool Normal,
    bool HesapAktifMi
);
