namespace HukukTakip.Api.Application.DTOs;

using HukukTakip.Api.Domain.Entities;

public record MusteriListDto(
    Guid Id,
    string MusteriNo,
    string? AdiUnvani,
    BorcluTipi BorcluTipi
);

public record MusteriDetailDto(
    Guid Id,
    string MusteriNo,
    string? AdiUnvani,
    BorcluTipi BorcluTipi,
    string? BorcluSoyadi,
    string? TCKN,
    DateOnly? DogumTarihi,
    string? DogumYeri,
    Cinsiyet? Cinsiyet,
    MedeniDurum? MedeniDurum,
    string? BabaAdi,
    string? AnneAdi,
    string? PasaportNumarasi,
    DateOnly? KimlikVerilisTarihi,
    string? NufusaKayitliOlduguIl,
    string? CiltNo,
    string? AileSiraNo,
    string? KutukSiraNo,
    string? SurucuBelgesiNumarasi,
    int? SehirId,
    int? IlceId,
    string? Semt,
    string? VergiDairesi,
    string? VergiNo,
    string? SSKNo,
    string? SSKIsyeriNumarasi,
    string? TicaretSicilNo,
    //string? ,
    string? BorcuTipi,
    MistiralMusteriTuru MusteriMusteriTipi,
    bool HayattaMi
);

public record MusteriCreateDto(
    string MusteriNo,
    string? AdiUnvani,
    BorcluTipi BorcluTipi,
    string? BorcluSoyadi,
    string? TCKN,
    DateOnly? DogumTarihi,
    string? DogumYeri,
    Cinsiyet? Cinsiyet,
    MedeniDurum? MedeniDurum,
    string? BabaAdi,
    string? AnneAdi,
    string? PasaportNumarasi,
    DateOnly? KimlikVerilisTarihi,
    string? NufusaKayitliOlduguIl,
    string? CiltNo,
    string? AileSiraNo,
    string? KutukSiraNo,
    string? SurucuBelgesiNumarasi,
    int? SehirId,
    int? IlceId,
    string? Semt,
    string? VergiDairesi,
    string? VergiNo,
    string? SSKNo,
    string? SSKIsyeriNumarasi,
    string? TicaretSicilNo,
    //string? BorcluTuru,
    string? BorcuTipi,
    MistiralMusteriTuru MusteriMusteriTipi,
    bool HayattaMi
);

public record MusteriUpdateDto(
    string MusteriNo,
    string? AdiUnvani,
    BorcluTipi BorcluTipi,
    string? BorcluSoyadi,
    string? TCKN,
    DateOnly? DogumTarihi,
    string? DogumYeri,
    Cinsiyet? Cinsiyet,
    MedeniDurum? MedeniDurum,
    string? BabaAdi,
    string? AnneAdi,
    string? PasaportNumarasi,
    DateOnly? KimlikVerilisTarihi,
    string? NufusaKayitliOlduguIl,
    string? CiltNo,
    string? AileSiraNo,
    string? KutukSiraNo,
    string? SurucuBelgesiNumarasi,
    int? SehirId,
    int? IlceId,
    string? Semt,
    string? VergiDairesi,
    string? VergiNo,
    string? SSKNo,
    string? SSKIsyeriNumarasi,
    string? TicaretSicilNo,
    //string? BorcluTuru,
    string? BorcuTipi,
    MistiralMusteriTuru MusteriMusteriTipi,
    bool HayattaMi
);
